import { imageUrl } from "@/data/links";
import { contact } from "../../../constent";

export const galleryPageData = {
  bannerData: {
    images: [imageUrl + "IMG_8174.webp"],
    title: "Gallery",
  },
  galleryLayoutData: {
    title: "EXPLORE",
    subTitle: "Anand Vardhan Resort",
  },
  images: [
    {
      id: 8,
      src: imageUrl + "Deluxe/001.webp",
      alt: "Deluxe room",
      tags: "Rooms & Suites",
    },
    {
      id: 9,
      src: imageUrl + "Deluxe/002.webp",
      alt: "Deluxe room",
      tags: "Rooms & Suites",
    },
    {
      id: 10,
      src: imageUrl + "Deluxe/003.webp",
      alt: "Deluxe room",
      tags: "Rooms & Suites",
    },
    {
      id: 11,
      src: imageUrl + "Deluxe/004.webp",
      alt: "Deluxe room",
      tags: "Rooms & Suites",
    },
    {
      id: 12,
      src: imageUrl + "Deluxe/005.webp",
      alt: "Deluxe room",
      tags: "Rooms & Suites",
    },
    {
      id: 13,
      src: imageUrl + "Deluxe/006.webp",
      alt: "Deluxe room",
      tags: "Rooms & Suites",
    },
    {
      id: 14,
      src: imageUrl + "Deluxe/007.webp",
      alt: "Deluxe room",
      tags: "Rooms & Suites",
    },
    {
      id: 15,
      src: imageUrl + "Deluxe/008.webp",
      alt: "Deluxe room",
      tags: "Rooms & Suites",
    },
    {
      id: 16,
      src: imageUrl + "superDeluxe/001.webp",
      alt: "Super Deluxe room",
      tags: "Rooms & Suites",
    },
    {
      id: 17,
      src: imageUrl + "superDeluxe/002.webp",
      alt: "Super Deluxe room",
      tags: "Rooms & Suites",
    },
    {
      id: 18,
      src: imageUrl + "superDeluxe/003.webp",
      alt: "Super Deluxe room",
      tags: "Rooms & Suites",
    },
    {
      id: 19,
      src: imageUrl + "superDeluxe/004.webp",
      alt: "Super Deluxe room",
      tags: "Rooms & Suites",
    },
    {
      id: 20,
      src: imageUrl + "superDeluxe/005.webp",
      alt: "Super Deluxe room",
      tags: "Rooms & Suites",
    },
    {
      id: 21,
      src: imageUrl + "superDeluxe/006.webp",
      alt: "Super Deluxe room",
      tags: "Rooms & Suites",
    },
    {
      id: 22,
      src: imageUrl + "superDeluxe/007.webp",
      alt: "Super Deluxe room",
      tags: "Rooms & Suites",
    },
    {
      id: 23,
      src: imageUrl + "superDeluxe/008.webp",
      alt: "Super Deluxe room",
      tags: "Rooms & Suites",
    },
    {
      id: 24,
      src: imageUrl + "luxurySuite/001.webp",
      alt: "Luxury room",
      tags: "Rooms & Suites",
    },
    {
      id: 25,
      src: imageUrl + "luxurySuite/002.webp",
      alt: "Luxury room",
      tags: "Rooms & Suites",
    },
    {
      id: 26,
      src: imageUrl + "luxurySuite/003.webp",
      alt: "Luxury room",
      tags: "Rooms & Suites",
    },
    {
      id: 27,
      src: imageUrl + "luxurySuite/004.webp",
      alt: "Luxury room",
      tags: "Rooms & Suites",
    },
    {
      id: 28,
      src: imageUrl + "luxurySuite/005.webp",
      alt: "Luxury room",
      tags: "Rooms & Suites",
    },
    {
      id: 29,
      src: imageUrl + "luxurySuite/006.webp",
      alt: "Luxury room",
      tags: "Rooms & Suites",
    },
    {
      id: 30,
      src: imageUrl + "luxurySuite/007.webp",
      alt: "Luxury room",
      tags: "Rooms & Suites",
    },
    {
      id: 31,
      src: imageUrl + "luxurySuite/008.webp",
      alt: "Luxury room",
      tags: "Rooms & Suites",
    },
    {
      id: 32,
      src: imageUrl + "luxurySuite/009.webp",
      alt: "Luxury room",
      tags: "Rooms & Suites",
    },
    {
      id: 6,
      src: imageUrl + "273A8341.webp",
      alt: "Reception lounge",
      tags: "RECEPTION",
    },
    {
      id: 112,
      src: imageUrl + "well3.webp",
      alt: "RECEPTION lounge",
      tags: "RECEPTION",
    },
    {
      id: 7,
      src: imageUrl + "273A8357.webp",
      alt: "Reception lounge",
      tags: "RECEPTION",
    },
    {
      id: 1,
      src: imageUrl + "IMG_8203.webp",
      alt: "Restaurant bar",
      tags: "RESTAURANT",
    },
    {
      id: 2,
      src: imageUrl + "IMG_8206.webp",
      alt: "Rooms & Suites",
      tags: "Rooms & Suites",
    },
    {
      id: 3,
      src: imageUrl + "IMG_8224.webp",
      alt: "Restaurant bar",
      tags: "RESTAURANT",
    },
    {
      id: 4,
      src: imageUrl + "273A8371.webp",
      alt: "Restaurant bar",
      tags: "RESTAURANT",
    },
    {
      id: 5,
      src: imageUrl + "273A8372.webp",
      alt: "Restaurant bar",
      tags: "RESTAURANT",
    },
    {
      id: 110,
      src: imageUrl + "well1.webp",
      alt: "Rishibhumi Wellness",
      tags: "Rishibhumi Wellness",
    },
    {
      id: 111,
      src: imageUrl + "well2.webp",
      alt: "Rishibhumi Wellness",
      tags: "Rishibhumi Wellness",
    },
    {
      id: 113,
      src: imageUrl + "well4.webp",
      alt: "Rishibhumi Wellness",
      tags: "Rishibhumi Wellness",
    },
    {
      id: 114,
      src: imageUrl + "well5.webp",
      alt: "Rishibhumi Wellness",
      tags: "Rishibhumi Wellness",
    },
    {
      id: 115,
      src: imageUrl + "well6.webp",
      alt: "Rishibhumi Wellness",
      tags: "Rishibhumi Wellness",
    },
    {
      id: 116,
      src: imageUrl + "well7.webp",
      alt: "Rishibhumi Wellness",
      tags: "Rishibhumi Wellness",
    },
    {
      id: 117,
      src: imageUrl + "well8.webp",
      alt: "Rishibhumi Wellness",
      tags: "Rishibhumi Wellness",
    },
    // {
    //   id: 118,
    //   src: imageUrl + "well1.jpg",
    //   alt: "Rishibhumi Wellness",
    //   tags: "Rishibhumi Wellness",
    // },
    // {
    //   id: 119,
    //   src: imageUrl + "well2.jpg",
    //   alt: "Rishibhumi Wellness",
    //   tags: "Rishibhumi Wellness",
    // },
    // {
    //   id: 120,
    //   src: imageUrl + "well3.jpg",
    //   alt: "Rishibhumi Wellness",
    //   tags: "Rishibhumi Wellness",
    // },
    // {
    //   id: 121,
    //   src: imageUrl + "well4.jpg",
    //   alt: "Rishibhumi Wellness",
    //   tags: "Rishibhumi Wellness",
    // },
    // {
    //   id: 122,
    //   src: imageUrl + "well5.jpg",
    //   alt: "Rishibhumi Wellness",
    //   tags: "Rishibhumi Wellness",
    // },
    // {
    //   id: 123,
    //   src: imageUrl + "well6.jpg",
    //   alt: "Rishibhumi Wellness",
    //   tags: "Rishibhumi Wellness",
    // },
    // {
    //   id: 124,
    //   src: imageUrl + "well7.jpg",
    //   alt: "Rishibhumi Wellness",
    //   tags: "Rishibhumi Wellness",
    // },
    {
      id: 35,
      src: imageUrl + "IMG_8354.webp",
      alt: "Open air cafe",
      tags: "Open air cafe",
    },
    {
      id: 99,
      src: imageUrl + "273A8474.webp",
      alt: "Activities",
      tags: "ACTIVITIES",
    },
    {
      id: 98,
      src: imageUrl + "273A8504.webp",
      alt: "Activities",
      tags: "ACTIVITIES",
    },
    {
      id: 97,
      src: imageUrl + "273A8535.webp",
      alt: "Activities",
      tags: "ACTIVITIES",
    },
    {
      id: 96,
      src: imageUrl + "273A8493.webp",
      alt: "Activities",
      tags: "ACTIVITIES",
    },
    {
      id: 95,
      src: imageUrl + "273A8501.webp",
      alt: "Activities",
      tags: "ACTIVITIES",
    },
    {
      id: 195,
      src: imageUrl + "img1.webp",
      alt: "Rishibhumi Wellness",
      tags: "Rishibhumi Wellness",
    },
    {
      id: 196,
      src: imageUrl + "img2.webp",
      alt: "Rishibhumi Wellness",
      tags: "Rishibhumi Wellness",
    },
    {
      id: 197,
      src: imageUrl + "img3.webp",
      alt: "Activities",
      tags: "EXTERIOR",
    },
    {
      id: 198,
      src: imageUrl + "img4.jpg",
      alt: "Activities",
      tags: "Activities",
    },
    {
      id: 36,
      src: imageUrl + "IMG_8370.webp",
      alt: "Open air cafe",
      tags: "Open air cafe",
    },
    {
      id: 37,
      src: imageUrl + "IMG_8377.webp",
      alt: "ROOMS & SUITES",
      tags: "ROOMS & SUITES",
    },
    {
      id: 38,
      src: imageUrl + "IMG_8380.webp",
      alt: "ROOMS & SUITES",
      tags: "ROOMS & SUITES",
    },
    {
      id: 39,
      src: imageUrl + "IMG_8383.webp",
      alt: "ROOMS & SUITES",
      tags: "ROOMS & SUITES",
    },
    {
      id: 40,
      src: imageUrl + "DSC_9716.webp",
      alt: "Hotel exterior",
      tags: "EXTERIOR",
    },
    {
      id: 34,
      src: imageUrl + "DSC_9726.webp",
      alt: "Hotel exterior",
      tags: "EXTERIOR",
    },
    {
      id: 41,
      src: imageUrl + "IMG_8238.webp",
      alt: "Activities",
      tags: "Activities",
    },
    {
      id: 42,
      src: imageUrl + "IMG_8241.webp",
      alt: "Activities",
      tags: "Activities",
    },
    {
      id: 43,
      src: imageUrl + "IMG_8254.webp",
      alt: "Open air cafe",
      tags: "Open air cafe",
    },
    {
      id: 44,
      src: imageUrl + "IMG_8255.webp",
      alt: "Open air cafe",
      tags: "Open air cafe",
    },
    {
      id: 45,
      src: imageUrl + "IMG_8258.webp",
      alt: "Open air cafe",
      tags: "Open air cafe",
    },
    {
      id: 46,
      src: imageUrl + "IMG_8262.webp",
      alt: "Garden area",
      tags: "EXTERIOR",
    },
    {
      id: 47,
      src: imageUrl + "IMG_8279.webp",
      alt: "Garden area",
      tags: "activities",
    },
    {
      id: 48,
      src: imageUrl + "273A8459.webp",
      alt: "Garden area",
      tags: "EXTERIOR",
    },
  ],

  addCardData: {
    title:
      "Experience the extraordinary at Anand Vardhan Resort",
    description:
      "Life's too short for ordinary vacations. Book now for memories that last forever.",
    link: {
      href: contact.cta,
      label: "Book Now",
    },
  },
};
